package tn.esprit.session;

import com.google.gson.Gson;
import com.google.gson.JsonObject;
import tn.esprit.entities.User;

import java.nio.charset.StandardCharsets;
import java.util.Base64;
import java.util.prefs.Preferences;

/**
 * JWT-based session manager for JavaFX application.
 * 
 * Replaces the traditional SessionManager with JWT token storage.
 * The JWT token contains all user information (id, email, role, etc.)
 * and is stored in Java Preferences for persistence across app restarts.
 * 
 * Benefits:
 * - Automatic "Remember Me" (token persisted on disk)
 * - Token expiration (security)
 * - Can be used for API calls
 * - No need to query database for user info
 */
public class JwtManager {
    
    private static final String PREF_KEY_JWT = "jwt_token";
    private static final Preferences PREFS = Preferences.userNodeForPackage(JwtManager.class);
    private static final Gson GSON = new Gson();
    
    // In-memory cache of current user (decoded from JWT)
    private static User currentUser = null;
    private static String currentToken = null;
    
    // ── Login ─────────────────────────────────────────────────────────────────
    
    /**
     * Store JWT token and decode user information.
     * 
     * @param jwtToken The JWT token (generated by JwtService)
     * @return The decoded User object, or null if token is invalid
     */
    public static User login(String jwtToken) {
        if (jwtToken == null || jwtToken.isBlank()) {
            return null;
        }
        
        // Validate token first
        if (!tn.esprit.services.JwtService.validateToken(jwtToken)) {
            System.err.println("[JwtManager] Invalid or expired token");
            return null;
        }
        
        // Decode JWT and extract user info
        User user = decodeToken(jwtToken);
        if (user == null) {
            return null;
        }
        
        // Store in memory
        currentUser = user;
        currentToken = jwtToken;
        
        // Persist to disk (for Remember Me)
        PREFS.put(PREF_KEY_JWT, jwtToken);
        
        System.out.println("[JwtManager] User logged in: " + user.getEmail() + " (JWT stored)");
        return user;
    }
    
    /**
     * Login with User object - generates JWT token automatically
     * 
     * @param user The authenticated user
     * @return The same user object
     */
    public static User login(User user) {
        if (user == null) {
            return null;
        }
        
        // Generate JWT token
        String jwtToken = tn.esprit.services.JwtService.generateToken(user);
        
        // Store token
        return login(jwtToken);
    }
    
    // ── Get Current User ──────────────────────────────────────────────────────
    
    /**
     * Get the currently logged-in user.
     * 
     * @return The current User, or null if not logged in
     */
    public static User getCurrentUser() {
        // Return cached user if available
        if (currentUser != null) {
            return currentUser;
        }
        
        // Try to restore from persisted JWT token
        String token = PREFS.get(PREF_KEY_JWT, null);
        if (token != null) {
            currentUser = decodeToken(token);
            currentToken = token;
            
            if (currentUser != null) {
                System.out.println("[JwtManager] Session restored from JWT: " + currentUser.getEmail());
            } else {
                // Token expired or invalid - clear it
                PREFS.remove(PREF_KEY_JWT);
            }
        }
        
        return currentUser;
    }
    
    /**
     * Get the current JWT token.
     * 
     * @return The JWT token, or null if not logged in
     */
    public static String getToken() {
        if (currentToken != null) {
            return currentToken;
        }
        
        // Try to restore from disk
        currentToken = PREFS.get(PREF_KEY_JWT, null);
        return currentToken;
    }
    
    // ── Check Authentication ──────────────────────────────────────────────────
    
    /**
     * Check if a user is currently logged in.
     * 
     * @return true if logged in, false otherwise
     */
    public static boolean isLoggedIn() {
        return getCurrentUser() != null;
    }
    
    /**
     * Check if the current user has a specific role.
     * 
     * @param role The role to check (e.g., "ADMIN", "ETUDIANT")
     * @return true if user has the role, false otherwise
     */
    public static boolean hasRole(String role) {
        User user = getCurrentUser();
        return user != null && role.equalsIgnoreCase(user.getRole());
    }
    
    /**
     * Check if the current user is an admin.
     */
    public static boolean isAdmin() {
        return hasRole("ADMIN");
    }
    
    /**
     * Check if the current user is a student.
     */
    public static boolean isStudent() {
        return hasRole("ETUDIANT");
    }
    
    // ── Logout ────────────────────────────────────────────────────────────────
    
    /**
     * Logout the current user and clear the JWT token.
     */
    public static void logout() {
        if (currentUser != null) {
            System.out.println("[JwtManager] User logged out: " + currentUser.getEmail());
        }
        
        // Clear memory
        currentUser = null;
        currentToken = null;
        
        // Clear disk
        PREFS.remove(PREF_KEY_JWT);
    }
    
    // ── JWT Decoding ──────────────────────────────────────────────────────────
    
    /**
     * Decode a JWT token and extract user information.
     * 
     * JWT format: header.payload.signature
     * We only decode the payload (no signature verification - trust Symfony)
     * 
     * @param jwtToken The JWT token
     * @return User object with decoded info, or null if invalid/expired
     */
    private static User decodeToken(String jwtToken) {
        try {
            // Split JWT into parts
            String[] parts = jwtToken.split("\\.");
            if (parts.length != 3) {
                System.err.println("[JwtManager] Invalid JWT format");
                return null;
            }
            
            // Decode payload (Base64 URL)
            String payload = parts[1];
            byte[] decodedBytes = Base64.getUrlDecoder().decode(payload);
            String decodedPayload = new String(decodedBytes, StandardCharsets.UTF_8);
            
            // Parse JSON
            JsonObject json = GSON.fromJson(decodedPayload, JsonObject.class);
            
            // Check expiration
            if (json.has("exp")) {
                long exp = json.get("exp").getAsLong();
                long now = System.currentTimeMillis() / 1000;
                if (now > exp) {
                    System.err.println("[JwtManager] Token expired");
                    return null;
                }
            }
            
            // Extract user info
            int userId = json.has("userId") ? json.get("userId").getAsInt() : 0;
            String email = json.has("email") ? json.get("email").getAsString() : "";
            String role = json.has("role") ? json.get("role").getAsString() : "";
            String prenom = json.has("prenom") ? json.get("prenom").getAsString() : "";
            String nom = json.has("nom") ? json.get("nom").getAsString() : "";
            String niveau = json.has("niveau") && !json.get("niveau").isJsonNull() 
                ? json.get("niveau").getAsString() : null;
            
            // Create appropriate User subclass based on role
            User user;
            if ("ETUDIANT".equalsIgnoreCase(role)) {
                tn.esprit.entities.Etudiant etudiant = new tn.esprit.entities.Etudiant();
                if (niveau != null) {
                    etudiant.setNiveau(niveau);
                }
                user = etudiant;
            } else if ("ADMIN".equalsIgnoreCase(role)) {
                user = new tn.esprit.entities.Admin();
            } else {
                // Default to Etudiant if role unknown
                user = new tn.esprit.entities.Etudiant();
            }
            
            // Set common fields
            user.setId(userId);
            user.setEmail(email);
            user.setRole(role);
            user.setPrenom(prenom);
            user.setNom(nom);
            
            return user;
            
        } catch (Exception e) {
            System.err.println("[JwtManager] Failed to decode JWT: " + e.getMessage());
            return null;
        }
    }
    
    // ── Token Refresh ─────────────────────────────────────────────────────────
    
    /**
     * Check if the token is about to expire (less than 1 hour remaining).
     * 
     * @return true if token should be refreshed
     */
    public static boolean shouldRefreshToken() {
        String token = getToken();
        if (token == null) return false;
        
        long remaining = tn.esprit.services.JwtService.getExpirationSeconds(token);
        
        // Refresh if less than 1 hour remaining
        return remaining > 0 && remaining < 3600;
    }
    
    /**
     * Refresh the current token (get a new one with extended expiration)
     * 
     * @return true if refresh successful, false otherwise
     */
    public static boolean refreshToken() {
        String oldToken = getToken();
        if (oldToken == null) return false;
        
        String newToken = tn.esprit.services.JwtService.refreshToken(oldToken);
        if (newToken == null) return false;
        
        // Update stored token
        currentToken = newToken;
        PREFS.put(PREF_KEY_JWT, newToken);
        
        System.out.println("[JwtManager] Token refreshed successfully");
        return true;
    }
    
    /**
     * Get token expiration time in seconds.
     * 
     * @return Seconds until expiration, or -1 if no token or error
     */
    public static long getTokenExpirationSeconds() {
        String token = getToken();
        if (token == null) return -1;
        
        return tn.esprit.services.JwtService.getExpirationSeconds(token);
    }
}
